### ISSUE TITLE
ProgrammingError when querying with exclude on reverse relation with tree fields

### ISSUE THREAD

**Issue by glennmatthews** [feincms/django-tree-queries#63]
First, thank you for this terrific library!

Hope this specific issue isn't too obscure... In our app, we have a TreeModel `Location`, and a set of models with foreign keys to `Location`, for example `PowerPanel`. We're working on upgrading from Django 3.2 to Django 4.2 (better late than never!) and have found that a subset of queries against Location now throw an exception on both PostgreSQL and MySQL:

```
>>> Location.objects.with_tree_fields().exclude(power_panels__isnull=False).exists()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "u0"
LINE 51: ...d" = ("dcim_location"."id") AND (__tree.tree_pk = U0.id)) OR...
                                                              ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
django.db.utils.ProgrammingError: missing FROM-clause entry for table "u0"
LINE 51: ...d" = ("dcim_location"."id") AND (__tree.tree_pk = U0.id)) OR...
                                                              ^
```

```
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'U0.id' in 'where clause'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/home/runner/work/nautobot/nautobot/nautobot/core/tests/test_filters.py", line 363, in test_filter_combined_name_exclude
    self.assertQuerysetEqualAndNotEmpty(qs, [self.locations[1]])
  File "/home/runner/work/nautobot/nautobot/nautobot/core/testing/mixins.py", line 229, in assertQuerysetEqualAndNotEmpty
    self.assertNotEqual(len(qs), 0, "Queryset cannot be empty")
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.11/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'U0.id' in 'where clause'")
```

The simplest query we've been able to reproduce the issue with so far is something along the lines of:

`Location.objects.with_tree_fields().exclude(power_panels__isnull=False)`

Here's the query on Postgres:

```
>>> print(Location.objects.with_tree_fields().exclude(power_panels__isnull=False).query)

    WITH RECURSIVE __tree (
        "tree_depth",
        "tree_path",
        "tree_ordering",
        "tree_pk"
    ) AS (
        SELECT
            0 AS tree_depth,
            array[T.id] AS tree_path,
            array["_name"]::text[] AS tree_ordering,
            T."id"
        FROM dcim_location T
        WHERE T."parent_id" IS NULL

        UNION ALL

        SELECT
            __tree.tree_depth + 1 AS tree_depth,
            __tree.tree_path || T.id,
            __tree.tree_ordering || "_name"::text,
            T."id"
        FROM dcim_location T
        JOIN __tree ON T."parent_id" = __tree.tree_pk
    )
    SELECT (__tree.tree_depth) AS "tree_depth", (__tree.tree_path) AS "tree_path", (__tree.tree_ordering) AS "tree_ordering", "dcim_location"."id", "dcim_location"."created", "dcim_location"."last_updated", "dcim_location"."_custom_field_data", "dcim_location"."parent_id", "dcim_location"."name", "dcim_location"."_name", "dcim_location"."location_type_id", "dcim_location"."status_id", "dcim_location"."tenant_id", "dcim_location"."description", "dcim_location"."facility", "dcim_location"."asn", "dcim_location"."time_zone", "dcim_location"."physical_address", "dcim_location"."shipping_address", "dcim_location"."latitude", "dcim_location"."longitude", "dcim_location"."contact_name", "dcim_location"."contact_phone", "dcim_location"."contact_email", "dcim_location"."comments" FROM "dcim_location" , "__tree" WHERE (NOT (EXISTS(
    WITH RECURSIVE __tree (
        "tree_depth",
        "tree_path",
        "tree_ordering",
        "tree_pk"
    ) AS (
        SELECT
            0 AS tree_depth,
            array[T.id] AS tree_path,
            array["_name"]::text[] AS tree_ordering,
            T."id"
        FROM dcim_location T
        WHERE T."parent_id" IS NULL

        UNION ALL

        SELECT
            __tree.tree_depth + 1 AS tree_depth,
            __tree.tree_path || T.id,
            __tree.tree_ordering || "_name"::text,
            T."id"
        FROM dcim_location T
        JOIN __tree ON T."parent_id" = __tree.tree_pk
    )
    SELECT 1 AS "a" FROM "dcim_powerpanel" U1 , "__tree" WHERE (U1."id" IS NOT NULL AND U1."location_id" = ("dcim_location"."id") AND (__tree.tree_pk = U0.id)) ORDER BY ("__tree".tree_ordering) ASC LIMIT 1)) AND (__tree.tree_pk = dcim_location.id)) ORDER BY ("__tree".tree_ordering) ASC
```

Some potentially relevant data points:

- Without the tree fields, no error:
    ```
    >>> Location.objects.without_tree_fields().exclude(power_panels__isnull=False).exists()
    True
    ```
- The issue is so far only seen with `.exclude()`; `.filter()` works just fine:
    ```
    >>> Location.objects.with_tree_fields().filter(power_panels__isnull=False).exists()
    False
    >>> Location.objects.with_tree_fields().filter(power_panels__isnull=True).exists()
    True
    ```
- This specific query did not raise an exception in Django 3.2, but we've seen a few other cases even in 3.2 where a `.exclude()` reported a similar exception; those were resolved by adding a `.without_tree_fields()` to the queries in question. **That may be our best option in this case as well?** (We perhaps foolishly made our manager class default to `with_tree_fields=True`, but in cases like this we don't actually *need* the tree annotation...)

Thanks again! We'll keep digging into potential workarounds in our app in the meantime.

**Comment by matthiask** [comment]
Hi @glennmatthews 

Thanks for the nice words and the explanation! I thought the problem happens because of #26 but that doesn't seem to be the case. What we have to do is skip the tree construction completely inside the `NOT(EXISTS(...))` subquery, but I'm not sure how to detect that. Something like #64 works locally for some versions, but relying on `a` being the only annotation looks and feels terrible.

**Comment by glennmatthews** [comment]
Thanks for the analysis! I agree the proposed fix there "feels" gross... it may be better to just document this as a case of "it hurts when I do this" (use `.with_tree_fields()` in places it isn't really needed) with the answer being "so don't do that". :-)

**Comment by matthiask** [comment]
I read Django's code again and think that comparing `query.annotations == {"a": Value(1)}` is good enough for us.

I have added a test which demonstrates that this case has been fixed and according to my rules https://406.ch/writing/my-rules-for-releasing-open-source-software/ this is good enough for a release. If you can verify that the fix works on your end that would be great of course, but it's not required.
